### ISSUE TITLE
3.7.0 build with a missing file

### ISSUE THREAD

**Issue by frederikspang** [queueit/KnownUser.V3.RubyOnRails#6]
Looking in:
```
~/PATH/TO/GEMS/gems/queueit_knownuserv3-3.7.0/lib/queueit_knownuserv3
```

The newly created file lib/queueit_knownuserv3/httpcontext_provider.rb seems to be missing.
It's in git, but most likely not released with 3.7.0.

Both our CI and local installs throws an error:

```
~/path/to/gems/queueit_knownuserv3-3.7.0/lib/queueit_knownuserv3.rb:1:in `require_relative': cannot load such file -- ~/path/to/gems/queueit_knownuserv3-3.7.0/lib/queueit_knownuserv3/httpcontext_provider (LoadError)
	from ~/path/to/gems/queueit_knownuserv3-3.7.0/lib/queueit_knownuserv3.rb:1:in `<top (required)>'
	from ~/path/to/ruby/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `require'
	from ~/path/to/ruby/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from ~/path/to/ruby/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
	from ~/path/to/ruby/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
	from ~/path/to/ruby/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
	from ~/path/to/ruby/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
	from ~/path/to/ruby/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
	from /app/config/application.rb:8:in `<top (required)>'
```

**Comment by frwiqueueit** [comment]
Thank you for bringing this to our attention. We will look into it.

**Comment by felixdrud** [comment]
I have release a new version (3.7.1) which includes the missing file. 3.7.0 has been yanked from RubyGems.

Please try again with the new version. I'll close this issue. Feel free to open it again if you are still experiencing problems.

**Comment by frederikspang** [comment]
Issue has disappeared.

Appreciate the swift response!
